version: '3.3'

services:
  axon-server:
    image: axoniq/axonserver
    hostname: axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - ${PWD}/axon/data:/data
      - ${PWD}/axon/events:/eventdata
      - ${PWD}/axon/config:/config




